### ISSUE TITLE
Horovod multi-gpu multi-node not working

### ISSUE THREAD

**Issue by gianscarpe** [PyTorchLightning/pytorch-lightning#10728]
## 🐛 Bug
Horovod doesn't work for multi-node, multi-gpu.
Each node has 4 gpus

### To Reproduce
Using basic example
```
horovodrun -np 8 -H gnode21:4,gnode23:4 python pl_examples/basic_examples/simple_image_classifier.py --trainer.gpus 1 --trainer.│
accelerator horovod
```
I got this error
```
[1,7]<stderr>:For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[1,6]<stderr>:Traceback (most recent call last):
[1,6]<stderr>:  File "pl_examples/basic_examples/simple_image_classifier.py", line 81, in <module>
[1,6]<stderr>:    cli_main()
[1,6]<stderr>:  File "pl_examples/basic_examples/simple_image_classifier.py", line 75, in cli_main
[1,6]<stderr>:    cli = LightningCLI(LitClassifier, MNISTDataModule, seed_everything_default=1234, save_config_overwrite=True)
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 289, in __init__
[1,6]<stderr>:    self.fit()
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/pytorch_lightning/utilities/cli.py", line 432, in fit
[1,6]<stderr>:    self.trainer.fit(**self.fit_kwargs)
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
[1,6]<stderr>:    self._run(model)
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 863, in _run
[1,6]<stderr>:    self.accelerator.setup_environment()
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu.py", line 33, in setup_environment
[1,6]<stderr>:    torch.cuda.set_device(self.root_device)
[1,6]<stderr>:  File "/home/gscarpellini/.conda/envs/unsup-exploration/lib/python3.7/site-packages/torch/cuda/__init__.py", line 311, in set_device
[1,6]<stderr>:    torch._C._cuda_setDevice(device)
[1,6]<stderr>:RuntimeError: CUDA error: invalid device ordinal
[1,6]<stderr>:CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
[1,6]<stderr>:For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Seems like gpu_adapter is using wrong device id (e.g., id 5, when per-node is are 0..3) for setDevice. 
I don't think the behavior is tested in CI for multi-node. Is it a known bug? @Borda @awaelchli 
### Environment

- PyTorch Lightning Version (e.g., 1.5.0): 1.4.9
- PyTorch Version (e.g., 1.10): 1.10
- Python version (e.g., 3.9): 3.7
- OS (e.g., Linux): CentoOS
- CUDA/cuDNN version: 11.3
- GPU models and configuration: Tesla 100, 2 nodes, 4 gpus each
- How you installed PyTorch (`conda`, `pip`, source):
- If compiling from source, the output of `torch.__config__.show()`:
- Any other relevant information: horovod 0.23.0

### Additional context

cc @tchaton @awaelchli

**Comment by chongxiaoc** [comment]
Horovod only has to set `gpu=1` in trainer.
Multiple-GPUs devices are set by horovod local rank separately.
I have an example here: https://github.com/horovod/horovod/pull/3290

**Comment by gianscarpe** [comment]
@chongxiaoc  I run the script with a gpu=1 as you can see from my script

**Comment by chongxiaoc** [comment]
Did you set up device with hvd.local_rank?
Sorry I didn't see `pl_examples/basic_examples/simple_image_classifier.py` on master branch.

**Comment by chongxiaoc** [comment]
Also, does horovod side exampel work for you?

**Comment by awaelchli** [comment]
Hello, thanks for reporting this and @chongxiaoc for helping out. 

Given the error above, it would be good to know what the values of
`trainer.accelerator.root_device`, 
`trainer.training_type_plugin.parallel_devices`, and
`trainer.training_type_plugin.local_rank` are. 

Could you print them out?

I suspect one of them is not correct, leading to `torch.cuda.set_device()` being called with a wrong value. Also, is this error coming from the first or the second node?

**Comment by gianscarpe** [comment]
Hi @awaelchli
This is the logging
`
[1,6]<stderr>:Root device cuda:6
[1,6]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,6]<stderr>:Local rank 6
[1,1]<stderr>:Root device cuda:1
[1,1]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,1]<stderr>:Local rank 1
[1,5]<stderr>:Root device cuda:5
[1,5]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,5]<stderr>:Local rank 5
[1,4]<stderr>:Root device cuda:4
[1,4]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,4]<stderr>:Local rank 4
[1,3]<stderr>:Root device cuda:3
[1,3]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,3]<stderr>:Local rank 3
[1,7]<stderr>:Root device cuda:7
[1,7]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
[1,7]<stderr>:Local rank 7
[1,2]<stderr>:Root device cuda:2
[1,2]<stderr>:Parallel devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3), device(type='cuda', index=4), device(t
ype='cuda', index=5), device(type='cuda', index=6), device(type='cuda', index=7)]
`
It seems that local rank and global rank are between 0-7. I believe local_rank should be between 0 and 3 (as I have 4 gpus per node), should'n it? Parallel devices are 0-7

**Comment by awaelchli** [comment]
I am surprised local rank returns values larger than 3. As you say, given your parameters, I would expect 0-4 on each node. This is strange because we retrieve the local rank by calling `horovod.local_rank()` directly.
https://github.com/PyTorchLightning/pytorch-lightning/blob/30ec4815cb0612689b30ab73988558f1aa1b6f76/pytorch_lightning/plugins/training_type/horovod.py#L60-L61

As for the parallel devices, it should contain cuda:0 through cuda:3. We determine the list here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/30ec4815cb0612689b30ab73988558f1aa1b6f76/pytorch_lightning/trainer/connectors/accelerator_connector.py#L924-L927

Again, we are calling `hvd.local_size()` which should return 4, not 8.

So I'm wondering if horovod doesn't detect your nodes correctly. I'll ping someone from horovod to check if they see something more here.

**Comment by irasit** [comment]
Not sure about horovodrun, but start lightning trainer with horovod backend using ray works for me when set up like this:
```
            self.ray_executor = RayExecutor(
                RayExecutor.create_settings(timeout_s=300),
                num_hosts=4,
                num_workers_per_host=2,
                gpus_per_worker=1,
            )```

**Comment by gianscarpe** [comment]
Thanks @awaelchli, I'm available if you need any help with testing/fixing this! :) 
@irasit Thansk for your message, how do you use ray executor? Never used it :)

**Comment by GiancarloPaoletti** [comment]
@gianscarpe using horovodrun to launch scripts always gave me headaches. A nice workaround (for non-SLURM clusters) is to use mpirun instead.

Assuming you loaded/installed the necessary modules (e.g., NCCL, OpenMPI, etc.), try to launch this command line:

`mpirun -np 8 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib -mca btl_tcp_if_exclude lo,docker0 -x HOROVOD_AUTOTUNE=1 -x HOROVOD_FUSION_THRESHOLD=33554432 -x HOROVOD_CYCLE_TIME=3.5 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=^virbr0,^docker0,lo -x LD_LIBRARY_PATH -x PATH python pl_examples/basic_examples/simple_image_classifier.py --trainer.gpus 1 --trainer.accelerator horovod`

Let me know if it works :)

**Comment by gianscarpe** [comment]
For everyone here, I found out that horovod needs to be installed with its specific PyTorch instead, otherwise it starts having strange behaviors. Sticking to the pytorch version, and launching with mpirun @GiancarloPaoletti , solved the issue :)
