### ISSUE TITLE
Trainig stuck before first epoch with `ddp` and multi-gpu 

### ISSUE THREAD

**Issue by AljoSt** [PyTorchLightning/pytorch-lightning#11910]
## 🐛 Bug

Training is stuck when using `ddp`, `gpus=[0, 1]`, and `num_sanity_val_steps=2`. The two validation checks are executed. The code execution seems to be stuck at `self.scaler.step(optimizer)` in `pre_optimizer_step` in `pytorch_lightning/plugins/precision/native_amp.py` and more specifically in pytorch at
https://github.com/pytorch/pytorch/blob/4f8b986e28736b59bc46cd0873a0f36fdaa6f5b8/torch/cuda/amp/grad_scaler.py#L284

If I either use `dp`, or `gpus=[0]`, or `num_sanity_val_steps=0`, the training runs normally (so any one of the changes means the code works)

Also, the code **works** with 
`torch==1.8.1+cu111`, `pytorch-lightning==1.3.8` 
`torch==1.10.2+cu113`, `pytorch-lightning==1.3.8`

code **does not work** with:
`torch==1.10.2+cu113`, `pytorch-lightning==1.4.0`
`torch==1.10.2+cu113`, `pytorch-lightning==1.5.10`

### To Reproduce

Annoyingly, I cannot reproduce the code with the BoringModel. 

### Environment

- PyTorch Lightning Version: 1.5.10
- PyTorch Version: 1.10.2+cu113
- Python version: 3.7
- OS: Ubuntu 18.04
- CUDA/cuDNN version: 11.6
- GPU models and configuration: 2*2080Ti
- How you installed PyTorch: pip
- Any other relevant information:
Code works pre pytorch-lightning `1.4.0`

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @carmocca

**Comment by awaelchli** [comment]
I also cannot reproduce with the boring model. Can you check if the optimizer state contains inf values, i.e., the `optimizer_state["found_inf_per_device"]`?

In this piece of code of the scaler, it calls into the `optimizer_step()`:

```py
    def _maybe_opt_step(self, optimizer, optimizer_state, *args, **kwargs):
        retval = None
        if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
            retval = optimizer.step(*args, **kwargs)
        return retval
```
If only one rank takes the branch and enters the step, while the other does not, this would explain the hang you are seeing.

**Comment by AljoSt** [comment]
Yeah, I tried to check that before (should have mentioned that). I cannot view what's inside. Both when debugging or when just inserting a print statement in the code.


    def _maybe_opt_step(self, optimizer, optimizer_state, *args, **kwargs):
        retval = None
        print("hi1")
        print(optimizer_state)
        print("hi2")
        if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
            retval = optimizer.step(*args, **kwargs)
        return retval

in this case it will print "hi1" but not "hi2". When I debug into it, I can't view the content either (it just doesn't print anything; even when I do `opimizerstate is None` it doesn't print anything)

**Comment by carmocca** [comment]
It's strange that `num_sanity_val_steps` which does not run optimization would impact the training optimization after.

**Comment by raman-rajarathinam** [comment]
Same here. Training stops after `epoch-0`. I am sorry I couldn't reproduce this issue with BoringModel.

I am using the below versions
```
pytorch-lightning = 1.5.10
torch             = 1.10.2+cu113
torchmetrics      = 0.7.2
```

and my trainer config looks like this
```
trainer.gpus=8 
trainer.max_epochs=100 
trainer.output_dir=$output_dir 
trainer.checkpoint_dir=$output_dir/ckpt_dir
trainer.val_check_interval=5026 
trainer.limit_train_batches=50260  # 10 validation steps  = 1 epoch
trainer.patience=30 
trainer.precision=16 
trainer.resume_from_checkpoint=True 
trainer.reload_dataloaders_every_epoch=True 
```

<img width="1440" alt="pl-training-issue" src="https://user-images.githubusercontent.com/16095608/155257057-ff5ca9e5-8ccb-4143-80e1-5b3eacb8ee33.png">

I am using NeptuneLogger and can successfully see the logs from `val-step-0` to `val-step-8` (9 steps), but not able to see `val-step-9` (10th step) as you can see from the image, that final validation step is taking considerable amount of time (~13 hrs) to get complete.

Would appreciate any help. Thanks

**Comment by raman-rajarathinam** [comment]
Just pointing out similar issue https://github.com/PyTorchLightning/pytorch-lightning/issues/11242.

**Comment by AljoSt** [comment]
Just as a clarification: For me the training is stuck before the first training step is executed. So after the validation-checks and before the second batch

**Comment by raman-rajarathinam** [comment]
> Just as a clarification: For me the training is stuck before the first training step is executed. So after the validation-checks and before the second batch

One possible reasons I could think of is that all the data workers might not have returned same no of batches, results in GPUs waiting indefinitely.

**Comment by qmpzzpmq** [comment]
I had same issue with it. And I replace the DDP sampler by myself, and set "drop_last=True" to make sure each node have the same number of batch. But It still on stuck on the last. But the funny things is if the limit_train_batch set to a int. it works fine.

**Comment by Eralien** [comment]
> I had same issue with it. And I replace the DDP sampler by myself, and set "drop_last=True" to make sure each node have the same number of batch. But It still on stuck on the last. But the funny things is if the limit_train_batch set to a int. it works fine.

It actually works!!! I also add limit_val_batches as a int. So interesting...

**Comment by awaelchli** [comment]
Hi, this is a very good lead to investigate! Nonetheless, extremely odd. If we look at the docs for distributed sampler:

**Comment by qmpzzpmq** [comment]
@awaelchli Hi, I have some experiment on it. And I figure it out what happen in my case.
The reaon of stuck on me:
The batch numer on each node is differenet, but the case of reason could be two:
1. as you said, drop last
2. same step are skiped as I mentioned previous: if same step are skiped in some node, which means, the i+1 step will be snyc with i step in others node. Then the DDP will stuck on last batch.

I have one suggestion, when `replace_ddp_sampler` is true. Please print the len of sampler, then the reason 1 is clear to avoid.
for reason 2, is it possible, if batch i in one node is skiped. Then we skip all i batch in each node. just for balance.

**Comment by awaelchli** [comment]
> same step are skiped as I mentioned previous: if same step are skiped in some node, which means, the i+1 step will be snyc with i step in others node. Then the DDP will stuck on last batch.

Yes, this is not allowed and will lead to the problem you describe. This should be avoided for DDP. #5243 has a discussion how to support skipping steps in DDP but it's still unclear how to do it properly.

**Comment by raman-rajarathinam** [comment]
> It actually works!!! I also add limit_val_batches as a int. So interesting...

Hi @Eralien , For me `limit_val_batches` and `limit_train_batches` were never an issue.

**Comment by vanpersie32** [comment]
> Just as a clarification: For me the training is stuck before the first training step is executed. So after the validation-checks and before the second batch

same here

**Comment by OedoSoldier** [comment]
Same here, btw what's your GPU? I'm using 4090 w/ torch 2.0.1+cu121. I tested on an A5000 w/ torch 1.13.1+cu118 and the code works just fine

**Comment by hooyahliu** [comment]
Same here, four 4090 GPUs with pytorch 1.12.1+cu11.6

**Comment by hooyahliu** [comment]
I have solved this problem. 
First of all, let me explain my situation: I use two 4090 GPUs, and because the dataset is too large, I used a function in DataLoader to randomly collect 1000 sets of data.
When running the program, I found that DataLoader ran the random data collection function twice, and then there was a stuck situation in the first epoch. 
I suspect that the data loaded on the two GPUs are inconsistent, that is, each GPU runs its own DataLoader. 
Therefore, I saved the dataset collected by DataLoader as a binary file in pt format and loaded this file instead of running DataLoader every time to ensure that the datasets on both GPUs are completely known. 
This successfully solved the problem.

**Comment by HitogamiAG** [comment]
Hello all! Faced with a similar problem (training stuck after the first epoch)
I used Kaggle GPUs T4x2 to train models, and when I switched to P100 training was dropped in the same place with an error (RuntimeError in on_train_epoch_end). Fixing this problem solved training stuck.

**Comment by zc-alexfan** [comment]
For me, DDP didn't seem to be the issue. The issue was when some modules got imported, it just hangs in the imports. By commenting out imports and uncommenting them, I figured out the imports that hangs. 

If you are using SLURM, the following script works for me:

```
#!/bin/bash -l

# SLURM SUBMIT SCRIPT
#SBATCH --nodes=1
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=32
#SBATCH --mem=128000
#SBATCH --partition=Nimble
#SBATCH --time=6-24:00:00
#SBATCH --output=/home/zicfan/nimble/IntrinsicAvatar/slurm_logs/slurm-%j.out  # Custom output file
#SBATCH --error=/home/zicfan/nimble/IntrinsicAvatar/slurm_logs/slurm-%j.err  # Custom error file

export CUDA_HOME=/mnt/nimble/zicfan/packages/cuda117
export PATH="$CUDA_HOME/bin:$PATH"
export CPATH="$CUDA_HOME/include:$CPATH"
export LD_LIBRARY_PATH="$CUDA_HOME/lib64/:$LD_LIBRARY_PATH"
export TORCH_HOME="/home/zicfan/nimble/torch_data"
export TORCH_MODEL_ZOO="/home/zicfan/nimble/torch_data"

source /mnt/nimble/zicfan/condas/myenv/bin/activate

cd /home/zicfan/myrepo
torchrun --nproc_per_node=4 --standalone launch.py dataset=xr_multi.yaml gpu=\"0,1,2,3\"
```

Another way to debug this is to see if a minimal dummy model works:

```
# train.py
import torch
import pytorch_lightning as L
import time

# STEP 1: DEFINE YOUR LIGHTNING MODULE
class ToyExample(L.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def training_step(self, batch):
        print("Rank", self.local_rank)
        # Send the batch through the model and calculate the loss
        # The Trainer will run .backward(), optimizer.step(), .zero_grad(), etc. for you
        loss = self.model(batch).sum()
        time.sleep(0.1)
        return loss

    def configure_optimizers(self):
        # Choose an optimizer or implement your own.
        return torch.optim.Adam(self.model.parameters())

# STEP 2: RUN THE TRAINER
if __name__ == "__main__":
    # Set up the model so it can be called in `training_step`.
    # This is a dummy model. Replace it with an LLM or whatever
    model = torch.nn.Linear(32, 2)
    pl_module = ToyExample(model)
    # Configure the dataset and return a data loader.
    train_dataloader = torch.utils.data.DataLoader(torch.randn(1000000, 32))
    trainer = L.Trainer(strategy="ddp", accelerator="gpu", devices=4)
    trainer.fit(pl_module, train_dataloader)
```

**Comment by iron-lion** [comment]
Just for others

I encountered the same issue: DDP, training fail after epoch 0 before epoch 1.
The issue was a custom callback function for dataloader reset that adjusts the dataloader parameters for each epoch.

Python 3.11.11
PyTorch 2.6.0+cu12.4
pytorch_lightning 2.5.0
