### ISSUE TITLE
One gpu 50% higher memory utilization than others?

### ISSUE THREAD

**Issue by exnx** [PyTorchLightning/pytorch-lightning#12651]
## 🐛 Bug

Hi, I am training ConvNext with 8 A100 gpus on GCP. When I am training with standard ConvNext-base, all 8 GPUs are utilized pretty evenly. However, I have this new layer (from the S4 paper) that I am swapping in for the group convolution in ConvNext. It runs, but then 1 gpu is at 39/40 GB, while the other 7 gpus are at 25/40 gpus, greatly limiting my training batch size :( And in turn, much slower, and costly with cloud credits.

As I was trying to investigate, here is something I found. The first gpu has 6 processes with ~2gb each memory each that were presumably supposed to be distributed to the other gpus, but for whatever reason, stuck to the first gpu.

Other than that, I have no idea even how to go about finding the source of the issue.

I was wondering if anyone had any hint on how to go about finding the problem? Any tips at all, ANY!, would be sooooo helpful. Thanks for your help.

I am using:
PTL 1.6, Python 3.8, Torch 1.11 cuda 11.3 (through conda)

Best,

Eric
![8gpus](https://user-images.githubusercontent.com/26887484/162097089-c5806dc8-d17a-44d2-8141-ee9d93d23a98.png)

cc @justusschock @kaushikb11 @awaelchli @akihironitta @rohitgr7 @borda

**Comment by krshrimali** [comment]
Hi, @exnx - Thank you for reporting this issue! In order to help debug, can you please share any reproduction script? I can check on our servers to see if we can reproduce this issue, and take from there.

**Comment by awaelchli** [comment]
Hello there!

> However, I have this new layer (from the S4 paper) that I am swapping in for the group convolution in ConvNext. It runs, but then 1 gpu is at 39/40 GB, while the other 7 gpus are at 25/40 gpus

This experiment that you did here hints at a problem with the layer's implementation. Could you share the implementation/reference? I couldn't find it. 

PyTorch Lightning does not modify the layers in the network. I would be surprised if this same observation doesn't occur in pure PyTorch. My general advice for such issues is to strip away every code that is unrelated to this issues until we end up with a minimal example. 

Finally, in your screenshot there appear to be extra processes on GPU 0. Could it be that these are zombie processes from a previous experiment holding on to memory? Make sure to kill them before running a new experiment, ensuring that memory usage is at 0 before launching the script. 

cheers

**Comment by exnx** [comment]
Hi, thanks so much for following up!  We found the bug, indeed it was an internal layer issue that we found, where we put something on cuda manualy.  Really appreciate your suggestions!
