### ISSUE TITLE
I tried to use GPU, but the memory overflowed. After that, I changed the batch size from 10 to 4, and it still overflowed. Excuse me, is it because I used manual back propagation?  RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 14.72 GiB already allocated; 7.75 MiB free; 14.76 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by Hou-jing** [PyTorchLightning/pytorch-lightning#12691]
I tried to use GPU, but the memory overflowed. After that, I changed the batch size from 10 to 4, and it still overflowed. Excuse me, is it because I used manual back propagation?  RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.90 GiB total capacity; 14.72 GiB already allocated; 7.75 MiB free; 14.76 GiB reserved in total by PyTorch)

**Comment by Hou-jing** [comment]
def training_step(self, batch, batch_idx):
        optimizer=self.optimizers()
        scheduler = self.lr_schedulers()

        # scheduler.zero_grad()
        """"""
        tf_board_logs = {
            "lr": self.trainer.optimizers[0].param_groups[0]['lr']
        }
        # tokens, token_type_ids, start_labels, end_labels, start_label_mask, end_label_mask, match_labels, sample_idx, label_idx = batch
        tokens, token_type_ids, all_span_idxs_ltoken,morph_idxs, span_label_ltoken, all_span_lens,all_span_weights,real_span_mask_ltoken,words,all_span_word,all_span_idxs = batch
        loadall = [tokens, token_type_ids, all_span_idxs_ltoken,morph_idxs, span_label_ltoken, all_span_lens,all_span_weights,
                   real_span_mask_ltoken, words, all_span_word, all_span_idxs]

        attention_mask = (tokens != 0).long()
        all_span_rep = self.forward(loadall,all_span_lens,all_span_idxs_ltoken,tokens, attention_mask, token_type_ids)#(batch,n_span,n_class)
        predicts = self.classifier(all_span_rep)#(batch,n_span,n_class）
        # print('all_span_rep.shape: ', all_span_rep.shape)

        output = {}
        if self.args.use_prune:
            span_f1s,pred_label_idx = span_f1_prune(all_span_idxs, predicts, span_label_ltoken, real_span_mask_ltoken)
        else:
            span_f1s = span_f1(predicts, span_label_ltoken, real_span_mask_ltoken)
        output["span_f1s"] = span_f1s
        loss = self.compute_loss(loadall,all_span_rep, span_label_ltoken, real_span_mask_ltoken,mode='train')
        optimizer.zero_grad()
        self.manual_backward(loss,retain_graph=True)
        #添加对抗扰动
        self.fgm.attack()
        all_span_rep_adv =self.forward(loadall,all_span_lens,all_span_idxs_ltoken,tokens, attention_mask, token_type_ids)#(batch,n_span,n_class)
        predicts_adv = self.classifier(all_span_rep_adv)  # (batch,n_span,n_class）
        loss_adv = self.compute_loss(loadall, all_span_rep, span_label_ltoken, real_span_mask_ltoken, mode='train')
        optimizer.zero_grad()
        self.manual_backward(loss_adv, retain_graph=True)
        self.fgm.restore()
        optimizer.step()
        scheduler.step()

        output[f"train_loss"] = loss_adv

        tf_board_logs[f"loss"] = loss_adv

        output['loss'] = loss_adv
        output['log'] =tf_board_logs

        return output

**Comment by semaphore-egg** [comment]
Maybe you should modify the issue caption to fewer than 20 words.
Have you tried with `nvidia-smi` to check if the previous failed launch correctly frees the GPU memory?

**Comment by Hou-jing** [comment]
I have solved this problem. 
In vaild_step,I put the following two lines of code, it is commented out

 # optimizer.zero_grad()
  #scheduler.zero_grad()
