### ISSUE TITLE
DDP init hangs with num_nodes >= 2 (with wrong global ranks?)

### ISSUE THREAD

**Issue by robogast** [PyTorchLightning/pytorch-lightning#4389]
## 🐛 Bug
practically, I'm doing the following:
```srun python train.py --num-nodes 2 --gpus 4```
Which results in the following hanging state, where multiple processes are assigned the same global rank:
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/8
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/8
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/8
LOCAL_RANK: 2 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/8
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/8
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
```

If the ddp init is handled by slurm (by manually setting --tasks-per-node=4), global ranks are initiated correctly, but I get a rendezvous error:
```python
File "/home/robertsc/.conda/envs/pytorch1.6/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Name or service not known
```

(but I'm not sure that is related, it might also be an error on my end)

 - PyTorch Version: 1.6
 - OS: Linux
 - How you installed PyTorch: conda
- How you installed PyTorch-Lightning: pip from source (pytorch-lightning-1.0.4rc1)
 - Python version: 3.8
 - CUDA/cuDNN/NCCL version: 10.1.243 / 7.6.5.32 / 2.6.4

**Comment by Xiaohan-Wang** [comment]
Same question here.
I tried `trainer = pl.Trainer(gpus=[4,7])`, and then the output was
```
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [4,7]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [4,7]
initializing ddp: GLOBAL_RANK: 7, MEMBER: 8/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1595629395347/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
```

**Comment by awaelchli** [comment]
@Xiaohan-Wang your error is not related to this issue here. what you report we fixed it in Lightning 1.0.4 (latest).

@robogast I know DDP a bit but unfortunately not much about SLURM.  "host not found: Name or service not known" sounds suspiciously like master address / port are not set. Can you confirm you have set them correctly? 
my suspicion is that it sees the same node twice somehow.

**Comment by robogast** [comment]
I fixed the latter issue by moving to a newer NCCL toolchain, so that was probably some config error on my end.
The former issue still stands though, also with my updated NCCL.

**Comment by hakanyi** [comment]
Same problem here -- let me know if I can help debugging. Thanks!

```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
...
LOCAL_RANK: 3 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Using native 16bit precision.
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
```

**Comment by robogast** [comment]
About the latter issue, where I got:
```python
File "/home/robertsc/.conda/envs/pytorch1.6/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
ValueError: host not found: Name or service not known
```
I added a print statement just above this LOC, and I got the following: 
```python
master_addr r29n5,r33n6,r34n1, master_port 22220, world_size 16, start_daemon False, timeout 0:30:00
```
So the reason it doesn't work is that the `os.environ['MASTER_ADDR']` is set to the address of multiple nodes.
I can hotfix it for myself with a `master_addr = master_addr.split(',')][0]`in `rendezvous.py`, but I hope someone can figure out why these addresses are wrongly set anyway (my guess is probably somewhere in `accelerators/accelerator.py` or `accelerators/ddp_slurm_accelerator.py`?)

**Comment by awaelchli** [comment]
@robogast see here someone figured it out, the fix is as you say to split the names: #5533

**Comment by mehmetfdemirel** [comment]
I am having the same problem, and do not understand what I need to do. I have installed `pytorch-lightning` via `pip`, which I thought would contain the updated source code. The file that they made the "fix" on (pytorch_lightning/trainer/connectors/slurm_connector.py) doesn't even exist anymore. Any suggestions?
