### ISSUE TITLE
Help with understanding unknown 'c10::Error' thrown during DDP training

### ISSUE THREAD

**Issue by neergaard** [PyTorchLightning/pytorch-lightning#4471]
## 🐛 Bug

This is not going to be a good and concise description, since I have no way of reproducing the error with 100% certainty. However, more and more I get these types of `c10::Error` instances thrown during training, both during the training phase and during the validation phase. I am running DDP on a single-node with 20 CPUs and 4 GPUs. The error is not located to any specific node. 

I don't think it's necessarily a PyTorch Lightning issue, so I am unsure whether it is appropriate here, but maybe someone has had similar experiences? 
```
terminate called after throwing an instance of 'c10::Error' 
  what():  CUDA error: initialization error 
Exception raised from insert_events at /opt/conda/conda-bld/pytorch_1595629427478/work/c10/cuda/CUDACachingAllocator.cpp:717 (most recent call first): 
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7fcc65f5177d in /home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/torch/lib/libc10.so) 
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x1130 (0x7fcc661a2370 in /home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/torch/lib/libc10_cuda.so) 
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7fcc65f3db1d in /home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/torch/lib/libc10.so) 
frame #3: <unknown function> + 0x53f29a (0x7fcca3ab529a in /home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/torch/lib/libtorch_python.so) 
frame #4: <unknown function> + 0x1241eb (0x55fadc0131eb in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #5: <unknown function> + 0x1243e6 (0x55fadc0133e6 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #6: _PyObject_GC_Malloc + 0x84 (0x55fadc0134d4 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #7: _PyObject_GC_New + 0xe (0x55fadc0134fe in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #8: PyFunction_NewWithQualName + 0x2e (0x55fadc0525be in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #9: _PyEval_EvalFrameDefault + 0x1918 (0x55fadc0bd9b8 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #10: _PyEval_EvalCodeWithName + 0xc30 (0x55fadc004160 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #11: _PyFunction_FastCallKeywords + 0x387 (0x55fadc054107 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #12: _PyEval_EvalFrameDefault + 0x416 (0x55fadc0bc4b6 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #13: _PyEval_EvalCodeWithName + 0x2f9 (0x55fadc003829 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #14: _PyFunction_FastCallKeywords + 0x387 (0x55fadc054107 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #15: _PyEval_EvalFrameDefault + 0x416 (0x55fadc0bc4b6 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #16: _PyEval_EvalCodeWithName + 0xc30 (0x55fadc004160 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #17: _PyFunction_FastCallKeywords + 0x387 (0x55fadc054107 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #18: _PyEval_EvalFrameDefault + 0x4a89 (0x55fadc0c0b29 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #19: _PyEval_EvalCodeWithName + 0xc30 (0x55fadc004160 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #20: _PyFunction_FastCallKeywords + 0x387 (0x55fadc054107 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #21: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #22: _PyFunction_FastCallDict + 0x10b (0x55fadc00485b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #23: _PyEval_EvalFrameDefault + 0x1e4a (0x55fadc0bdeea in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #24: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #25: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #26: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #27: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #28: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #29: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #30: _PyFunction_FastCallDict + 0x10b (0x55fadc00485b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #31: _PyObject_Call_Prepend + 0x63 (0x55fadc0234d3 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #32: <unknown function> + 0x16bd5a (0x55fadc05ad5a in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #33: _PyObject_FastCallKeywords + 0x128 (0x55fadc05b968 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #34: _PyEval_EvalFrameDefault + 0x49e6 (0x55fadc0c0a86 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #35: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #36: _PyEval_EvalFrameDefault + 0x4a89 (0x55fadc0c0b29 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #37: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #38: _PyEval_EvalFrameDefault + 0x4a89 (0x55fadc0c0b29 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #39: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #40: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #41: _PyEval_EvalCodeWithName + 0x5da (0x55fadc003b0a in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #42: _PyFunction_FastCallDict + 0x1d5 (0x55fadc004925 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #43: _PyObject_Call_Prepend + 0x63 (0x55fadc0234d3 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #44: <unknown function> + 0x16bd5a (0x55fadc05ad5a in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #45: _PyObject_FastCallKeywords + 0x128 (0x55fadc05b968 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #46: _PyEval_EvalFrameDefault + 0x49e6 (0x55fadc0c0a86 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #47: _PyFunction_FastCallDict + 0x10b (0x55fadc00485b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #48: <unknown function> + 0x16349a (0x55fadc05249a in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #49: PyObject_GetIter + 0x16 (0x55fadc002d76 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #50: <unknown function> + 0x1b91dc (0x55fadc0a81dc in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #51: _PyMethodDef_RawFastCallKeywords + 0x1e4 (0x55fadc054884 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #52: _PyCFunction_FastCallKeywords + 0x21 (0x55fadc054a31 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #53: _PyEval_EvalFrameDefault + 0x46f5 (0x55fadc0c0795 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #54: <unknown function> + 0x16cfb4 (0x55fadc05bfb4 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #55: <unknown function> + 0x177b6f (0x55fadc066b6f in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #56: <unknown function> + 0x16d575 (0x55fadc05c575 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #57: _PyMethodDef_RawFastCallKeywords + 0xe9 (0x55fadc054789 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #58: _PyCFunction_FastCallKeywords + 0x21 (0x55fadc054a31 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #59: _PyEval_EvalFrameDefault + 0x46f5 (0x55fadc0c0795 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #60: <unknown function> + 0x16cfb4 (0x55fadc05bfb4 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #61: _PyEval_EvalFrameDefault + 0xa46 (0x55fadc0bcae6 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #62: _PyFunction_FastCallKeywords + 0xfb (0x55fadc053e7b in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
frame #63: _PyEval_EvalFrameDefault + 0x6a0 (0x55fadc0bc740 in /home/groups/mignot/miniconda3/envs/nml/bin/python) 
Traceback (most recent call last): 
  File "/home/users/alexno/sleep-staging/train.py", line 194, in <module> 
    run_training() 
  File "/home/users/alexno/sleep-staging/train.py", line 147, in run_training 
    trainer.fit(model, dm) 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 440, in fit 
    results = self.accelerator_backend.train() 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 146, in train 
    results = self.ddp_train(process_idx=self.task_idx, model=model) 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 279, in ddp_train 
    results = self.train_or_test() 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test 
    results = self.trainer.train() 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 483, in train 
    self.train_loop.run_training_epoch() 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 541, in run_training_epoch 
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx) 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 687, in run_training_batch 
    self.log_training_step_metrics(opt_closure_result, batch_callback_metrics, batch_log_metrics) 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 501, in log_training_step_metrics 
    self.trainer.logger_connector.add_progress_bar_metrics(step_pbar_metrics) 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/logger_connector.py", line 105, in add_progress_bar_metrics 
    v = v.item() 
  File "/home/groups/mignot/miniconda3/envs/nml/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler 
    _error_if_any_worker_fails() 
RuntimeError: DataLoader worker (pid 51292) is killed by signal: Aborted.
```

### Environment
```
* CUDA:
        - GPU:
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
                - Tesla V100-SXM2-16GB
        - available:         True
        - version:           10.2
* Packages:
        - numpy:             1.19.2
        - pyTorch_debug:     False
        - pyTorch_version:   1.6.0
        - pytorch-lightning: 1.0.2
        - tensorboard:       2.3.0
        - tqdm:              4.51.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - 
        - processor:         x86_64
        - python:            3.7.9
        - version:           #1 SMP Mon Jul 29 17:46:05 UTC 2019
```
### Additional context

Please let me know if this is more suited towards the PyTorch team.

**Comment by s-rog** [comment]
Yeah this is a pytorch/cuda issue rather than lightning, though I would start by looking at your env setup and dataloader code.
I'll close this for now, if you find that the issue is caused by lightning, feel free to re-open!

**Comment by neergaard** [comment]
That's totally fair, I wasn't exactly sure where the culprit was, and the question was extremely vague anyways.

The only reason for me thinking that PL could be the cause, was because I only get these errors when running DDP training on a single-node multi-GPU system. It works fine for single-node single-GPU on the same system (at least I haven't come across one yet).

**Comment by s-rog** [comment]
Have you tried DDP without lightning? I suspect you would run into the same issues, if you are only running into issues with multi gpu I would suggest looking into your NCCL setup (or whichever backend you are using) as well.

**Comment by neergaard** [comment]
@s-rog No, I am not super familiar with the setup for DDP training using raw PyTorch, that's why PL is attractive to me :) 

Anyways, I found that using the Metrics package was disturbing the training somehow: I had instantiated a `self.train_acc` attribute using `pl.metrics.Accuracy`, which is called in the training step using `self.log('train_acc', self.train_acc)`, and disabling this actually made the issue go away completely. Don't understand why though.

**Comment by chris89culley** [comment]
I had exactly the same error and removing the log solved this for me too. Does anyone know why this would be?

**Comment by evancasey** [comment]
I was able to get around this by upgrading versions of pytorch/cuda/cudnn to their latest

**Comment by evancasey** [comment]
Seeing the same issue here with pytorch 1.9, cudatoolkit 11.0.3, pytorch-lightning 1.4.1

**Comment by ChenYingpeng** [comment]
Seeing the same issue here with pytorch 1.7.1, cuda-10.0, pytorch-lightning 1.3.3.

**Comment by nik-sm** [comment]
Seeing this issue as well. 

I re-ran the same code twice to check whether this was a sporadic issue - same error at the same point in the code (after ~18 epochs of training).

I ran an MNIST example (https://github.com/pytorch/examples/blob/master/mnist/main.py) on 1 GPU and on 8 GPUs (without using pytorch-lightning) and found no problem. 

Anyone have advice on how to further debug the problem? Is it possible there is a slow resource leak that only becomes apparent when training a large model on a large dataset?


My version info using https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py is below, and the stack trace that I encounter is attached.

```
Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.9.6 (default, Jul  3 2021, 17:50:42)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1054-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80
GPU 2: Tesla K80
GPU 3: Tesla K80
GPU 4: Tesla K80
GPU 5: Tesla K80
GPU 6: Tesla K80
GPU 7: Tesla K80

Nvidia driver version: 470.57.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.910
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.1
[pip3] pytorch-lightning==1.4.2
[pip3] torch==1.9.0
[pip3] torchmetrics==0.5.0
[pip3] torchvision==0.10.0
[conda] Could not collect
```

[stack-trace.txt](https://github.com/PyTorchLightning/pytorch-lightning/files/7000521/stack-trace.txt)

**Comment by nik-sm** [comment]
Just to briefly follow-up - I don't have a short repro for this at the moment and I can't share the full code in which I encountered this issue, but basically this seems to be a PL 1.4 issue. 

After tearing out features from my code (and my hair), I eventually realized this seems to be an issue present in only some versions.
Unsure whether it was a torch or PL bug, I tried most of the cross product of: PL [1.3.8, 1.4.1, 1.4.2] and torch [1.7.1, 1.8.0, 1.8.1, 1.9.0]

Basically: using PL 1.3.8 always worked - using 1.4+ always failed.
The only additional informative point is that using 1.4+ with 1.9.0 failed sooner (after 12 epochs on 4 GPUs over a large dataset), and with 1.8.0 a bit later (after 23 epochs on same setup).

This seems like it indicates some missing integration tests, but I know there are a huge number of features and it's not an easy thing to ask for.

One last comment - https://github.com/PyTorchLightning/pytorch-lightning/issues/8821 seems like it might or might not be related

**Comment by nik-sm** [comment]
@s-rog

**Comment by skull8888888** [comment]
I have exactly same issue but only during validation and specifically with `ddp` and not with `dp`. PL version is `1.4.4`

**Comment by cobalamin** [comment]
Me too, but I was able to solve it by adding the `rank_zero_only=True` option mentioned in the comment here https://github.com/PyTorchLightning/pytorch-lightning/issues/8821#issuecomment-902402784 . I'm also using ddp, and it has been occurring exactly as described here since I updated to 1.4.

**Comment by saltoricristiano** [comment]
The solution [#8821 (comment)](https://github.com/PyTorchLightning/pytorch-lightning/issues/8821#issuecomment-902402784) worked for m too! (PL 1.4.1, Pytorch 1.8.0, CUDA 11.1)!

**Comment by kingmbc** [comment]
- Env: ubuntu18.04, python3.7, cuda11.1, cudnn8.0, pytorch1.9.0, PL 1.4.2
Finally, # 8821 saved me for DDP.

To solve this issue, I had several things and experiences. 
For example, if I reduced BATCH_SIZE or reduce NUM_WORKERS of the DataLoader, my code works slightly but was stuck back after a few epochs.

**Comment by mahieyin-rahmun** [comment]
I have been facing this error too with PL 1.4.5, PyTorch 1.8.1 and CUDA 10.1 on 8 Tesla K80s. Multi GPU training crashes but it keeps training with 1 GPU. However, once I set the distributed_backend to "gloo", it works now.

**Comment by eagle-dot** [comment]
I  had similar issues when running the alexNet . It was related to the  file opening.   After I download the dataset and store locally, run the program like build/dnn .

We need to download cifar 10 dataset and put in the folder as the same level of build
./build
./cifar-10-batches-bin
  /data_batch_1.bin
  /data_batch_2.bin
  /data_batch_3.bin
  /data_batch_4.bin
  /data_batch_5.bin
  /batches.meta.txt
  /test_batch.bin

  ```
then run build/dnn   Hope that might be useful.

**Comment by csiki** [comment]
In my case, setting rank_zero_only=True as mentioned above, and leaving pin_memory=False solved the issue.
