### ISSUE TITLE
0.5.3 broke DDP vs 0.5.2.1

### ISSUE THREAD

**Issue by s-rog** [PyTorchLightning/pytorch-lightning#555]
Using ddp on 0.5.3.2 would cause a gpu worker to crash at an epoch transition (start of epoch 7 for me) and hang the whole training process. I rolled back to 0.5.2.1 (used for my last project) and the issue was gone. Single gpu training works fine on both versions and toggling amp makes no difference. I'm using pytorch 1.3 in NGC 19.10-py3.

Any ideas on how to debug this? since it just hangs without an error code...

Edit:
Should add that I don't have any special hooks/functions running at the start of epochs

**Comment by awaelchli** [comment]
First I would check if this happens with the pl examples in this repository, e.g. the MNIST. If not, it would be good to have code for a minimal example to reproduce it.

**Comment by jeffling** [comment]
I'm using ddp with 0.5.3.2 and it is working fine. Is there any error message?

**Comment by s-rog** [comment]
Unfortunately no, all I see is a child process crash in htop and nvtop/nvidia-smi while training hangs, I suspect it might have something to do with the recurrent parts of my model, but then I just finished running 100 training runs on 0.5.2.1 with no issues at all... when 0.5.3.2 crashes during the first run

**Comment by jeffling** [comment]
Are you able to come up with a reproducible code snippet you could share?

**Comment by s-rog** [comment]
<details>
<summary>NCCL init log</summary>

```
[0] NCCL INFO Bootstrap : Using [0]eth0:10.42.0.4<0>
[0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_6
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_8
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_1
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_3
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_5
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_7
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_9
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_0
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_2
[0] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[0] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_4
[0] NCCL INFO NET/IB : No device found.
[0] NCCL INFO NET/Socket : Using [0]eth0:10.42.0.4<0>
NCCL version 2.4.8+cuda10.1
[1] NCCL INFO Bootstrap : Using [0]eth0:10.42.0.4<0>
[1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_6
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_8
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_1
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_3
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_5
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_7
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_9
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_0
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_2
[1] misc/ibvwrap.cc:212 NCCL WARN Call to ibv_open_device failed
[1] transport/net_ib.cc:117 NCCL WARN NET/IB : Unable to open device mlx5_4
[1] NCCL INFO NET/IB : No device found.
[1] NCCL INFO NET/Socket : Using [0]eth0:10.42.0.4<0>
[0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
[0] NCCL INFO NCCL_LL_THRESHOLD set by environment to 0.
[1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
[1] NCCL INFO NCCL_LL_THRESHOLD set by environment to 0.
[0] NCCL INFO Channel 00 :    0   1
[0] NCCL INFO Channel 01 :    0   1
[0] NCCL INFO Channel 02 :    0   1
[0] NCCL INFO Channel 03 :    0   1
[0] NCCL INFO Ring 00 : 0[1] -> 1[2] via P2P/IPC
[1] NCCL INFO Ring 00 : 1[2] -> 0[1] via P2P/IPC
[0] NCCL INFO Ring 01 : 0[1] -> 1[2] via P2P/IPC
[1] NCCL INFO Ring 01 : 1[2] -> 0[1] via P2P/IPC
[0] NCCL INFO Ring 02 : 0[1] -> 1[2] via P2P/IPC
[1] NCCL INFO Ring 02 : 1[2] -> 0[1] via P2P/IPC
[0] NCCL INFO Ring 03 : 0[1] -> 1[2] via P2P/IPC
[1] NCCL INFO Ring 03 : 1[2] -> 0[1] via P2P/IPC
[0] NCCL INFO Using 256 threads, Min Comp Cap 7, Trees disabled
[0] NCCL INFO comm 0x7f351c002400 rank 0 nranks 2 cudaDev 0 nvmlDev 1 - Init COMPLETE
[1] NCCL INFO comm 0x7f20c4002400 rank 1 nranks 2 cudaDev 1 nvmlDev 2 - Init COMPLETE
[0] NCCL INFO Launch mode Parallel
```
</details>

There were no NCCL log entries during training or when the crash happens, these are the NCCL logs during initialization. This notebook instance has 4 GPUS but my training script was running with 2.

**Comment by jeffling** [comment]
As a sanity check, could you run your model on a single GPU that isn't 0? As in use gpus=[1] or whichever GPU crashes.

**Comment by s-rog** [comment]
I ran the example on only gpu 1 and it ran fine (0.5.3)

**Comment by jeffling** [comment]
@s-rog More questions, thanks so much for spending the time to help debug. 

Does it always fail at the same point? 
When does it fail? 
Is it always the same GPU that fails? 
How are you running this? Is it inside docker (you mentioned a container)?

We recently switched to pytorch 1.3 and will be doing some DDP as well. I can see if I can replicate it.

**Comment by s-rog** [comment]
It fails around the same epoch
For the example it's the end of the 15th epoch if I recall correctly
The GPU that fails seem pretty random
Yes, in a nvidia/jupyter docker (though I'm running training in terminals instead notebooks)

**Comment by jeffling** [comment]
Could you make sure you have enough RAM to run all of your processes inside said docker container? The docker OOM Killer could be killing a random process inside your container. 

You can also disable the OOM killer https://docs.docker.com/engine/reference/run/#user-memory-constraints

**Comment by s-rog** [comment]
This instance is running with 755GB of ram so should be fine haha

**Comment by s-rog** [comment]
Another update, just tried running teh example code on pytorch 1.2 (ngc 1.09) and the problem still remains on 0.5.3.2

**Comment by s-rog** [comment]
any luck recreating the issue? or is there anything else I can do on my end?

**Comment by jeffling** [comment]
Things seem to be working for me... I'll try with the example code soon. 

Does this fail if you run it outside of docker?

**Comment by s-rog** [comment]
Running bare metal would require quite a lot of setup on my end, I'll see what I can do. I have however just tried running on the bare NGC pytorch image (usually has modifications to fit my workflow) and the issue persists.

Could this be related to running on a dual socket system?

**Comment by jeffling** [comment]
@s-rog I'm afraid I'm not familiar with it. Is there a cloud setup on GCP/AWS you think could be close to your setup that I can try replicating with?

**Comment by s-rog** [comment]
I looked at GCP/AWS listings but couldn't find any info on sockets. But my setup here is with two of these.
`Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz`

**Comment by s-rog** [comment]
I think I have identified the issue: early stopping. I pulled the latest commit and early stopping prints. But I assume it's broken and doesn't stop training correctly, producing the symptoms I described above. @jeffling 

On another note, early stopping should not be on  by default.

**Comment by williamFalcon** [comment]
max_nb_epochs is deprecated I believed. new docs should show this.

**Comment by williamFalcon** [comment]
@luiscape

**Comment by s-rog** [comment]
I see, should have pulled the new examples as well. However, is there any way to make lightning exit training correctly in DDP?

**Comment by joyousprakhar** [comment]
Is it resolved?
My process is getting frozen when EarlyStopping tries to stop the training while using DDP with 4 GPUS. It seems to stop correctly when calling EarlyStopping on a single GPU with DDP. Also, DP works as well with 4 GPUS

**Comment by williamFalcon** [comment]
upgrade to 0.8.5
