### ISSUE TITLE
Training stops at 54 epoch in DP setting

### ISSUE THREAD

**Issue by hiun** [PyTorchLightning/pytorch-lightning#5750]
## 🐛 Bug

- I am using https://huggingface.co/google/mt5-base model for seq2seq training
- The training-eval loop is typical Pytorch Lightning class
### problem
- The training program stops after completing validation step of specific epoch (always 54 epoch)
- No error logs, just stops
- It occurs in multi DP using 4 or more GPUs. (Seems not occur in single or 2 GPU setting)
  - I think It seems it is the effect of early stopping, but the same happens with I pass early stopping patient to `200`
- In addition, on 4-GPU DDP setting, a hang occurs in 54 epoch (process not stops, but GPU usages drops training stops)
- Any comment or suggestions for resolving this issues are appreciated
```
Epoch 54:  99%|█████████▉| 2914/2950 [1:01:19<00:45,  1.26s/it, loss=0.541, v_num=0]
Epoch 54:  99%|█████████▉| 2918/2950 [1:01:31<00:40,  1.27s/it, loss=0.541, v_num=0]
Validating:  90%|█████████ | 254/282 [13:04<01:25,  3.04s/it]
Validating:  94%|█████████▎| 264/282 [13:36<01:02,  3.50s/it]
Validating:  97%|█████████▋| 274/282 [14:09<00:26,  3.33s/it]
Epoch 54: 100%|██████████| 2950/2950 [1:03:38<00:00,  1.29s/it, loss=0.541, v_num=0]
```

---
-  (another question) How to disable early stopping? Currently, [doc](https://pytorch-lightning.readthedocs.io/en/latest/early_stopping.html) seems not mentions disabling early stopping 

## Please reproduce using the BoringModel
- I will prepare and add later.

### Environment
- Pytorch 1.5.1
- PL 1.1.3
- GPU driver : 440.33.01 or higher

**Comment by kaushikb11** [comment]
@hiun Could you please share the code in collab to reproduce the bug?

**Comment by marrrcin** [comment]
> In addition, on 4-GPU DDP setting, a hang occurs in 54 epoch (process not stops, but GPU usages drops training stops)

Might be related to https://github.com/PyTorchLightning/pytorch-lightning/issues/5604

**Comment by hiun** [comment]
This issue is caused by my code mistake. 
I accidentally give a small (54) to max epoch value, after adjust the max epoch value, works fine on DP or CPU environment.
DDP also hangs after the max epoch which seems is interpretable behavior, but not normal behavior. (currently I don't know why.)

**Comment by hiun** [comment]
@marrrcin 
Thank you for your reply. 
The root cause of the problem is now resolved, but still strange happen as I described in https://github.com/PyTorchLightning/pytorch-lightning/issues/5750#issuecomment-785988122. 

I will read your referenced issue. and reopen this issue if I have some findings.
