### ISSUE TITLE
Freeze on restore from checkpoint

### ISSUE THREAD

**Issue by Rizhiy** [PyTorchLightning/pytorch-lightning#7638]
## 🐛 Bug

Sometimes restoring from checkpoint causes the trainer to go into infinite cylce: 100% GPU usage, no progress.

## Please reproduce using the BoringModel

I can't reproduce in Colab, since I don't have 2 GPUs there, but here is python code:
```python
"""
# The Boring Model
Replicate a bug you experience, using this model.

[Remember! we're always available for support on Slack](https://join.slack.com/t/pytorch-lightning/shared_invite/zt-f6bl2l0l-JYMK3tbAgAmGRrlNr00f1A)

---
## Setup env
"""

"""---
## Deps
"""
from pathlib import Path
from uuid import uuid4
from pytorch_lightning.plugins import DDPPlugin

from pytorch_lightning.callbacks.model_checkpoint import ModelCheckpoint
import os

import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split, Dataset
from torchvision.datasets import MNIST
from torchvision import transforms
import pytorch_lightning as pl
from shutil import rmtree
from pytorch_lightning.metrics.functional import accuracy
tmpdir = os.getcwd()

"""---
## Data
Random data is best for debugging. If you needs special tensor shapes or batch compositions or dataloaders, modify as needed
"""

# some other options for random data
from pl_bolts.datasets import RandomDataset, DummyDataset, RandomDictDataset

class RandomDataset(Dataset):
    def __init__(self, size, num_samples):
        self.len = num_samples
        self.data = torch.randn(num_samples, size)

    def __getitem__(self, index):
        return self.data[index]

    def __len__(self):
        return self.len

num_samples = 10000

train = RandomDataset(32, num_samples)
train = DataLoader(train, batch_size=32)

val = RandomDataset(32, num_samples)
val = DataLoader(val, batch_size=32)

test = RandomDataset(32, num_samples)
test = DataLoader(test, batch_size=32)


import torch
from pytorch_lightning import LightningModule
from torch.utils.data import Dataset

class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.layer = torch.nn.Linear(32, 2)

    def forward(self, x):
        return self.layer(x)

    def loss(self, batch, prediction):
        # An arbitrary loss to have a loss that updates the model weights during `Trainer.fit` calls
        return torch.nn.functional.mse_loss(prediction, torch.ones_like(prediction))

    def training_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        return {"loss": loss}

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def validation_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log("loss", loss)
        return {"x": loss}

    def validation_epoch_end(self, outputs) -> None:
        torch.stack([x['x'] for x in outputs]).mean()

    def test_step(self, batch, batch_idx):
        output = self.layer(batch)
        loss = self.loss(batch, output)
        self.log('fake_test_acc', loss)
        return {"y": loss}

    def test_epoch_end(self, outputs) -> None:
        torch.stack([x["y"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.layer.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]

"""---
## Define the test
NOTE: in colab, set progress_bar_refresh_rate high or the screen will freeze because of the rapid tqdm update speed.
"""
ckpt_dir = Path("/tmp") / str(uuid4())
def _create_trainer(remove_checkpoint=True, **kwargs):
    checkpoint_callback = ModelCheckpoint(
        monitor="loss",
        mode="min",
        filename="{step:05d}",
        every_n_train_steps=30,
        save_top_k=1,
        save_last=True,
    )
    if remove_checkpoint:
        rmtree(ckpt_dir, ignore_errors=True)
    last_checkpoint_path = ckpt_dir / "lightning_logs" / "version_0" / "checkpoints" / "last.ckpt"
    return pl.Trainer(
        default_root_dir=ckpt_dir,
        gpus=2,
        accelerator="ddp",
        auto_select_gpus=True,
        max_epochs=1,
        progress_bar_refresh_rate=20,
        sync_batchnorm=True,
        plugins=DDPPlugin(find_unused_parameters=False),
        resume_from_checkpoint=last_checkpoint_path if last_checkpoint_path.exists() else None,
        callbacks=[checkpoint_callback],
        **kwargs
    )

def test_normal():
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = _create_trainer(precision=32)

    # Train the model ⚡
    trainer.fit(model, train, val)

    trainer.test(test_dataloaders=test)

def test_another():
    model = BoringModel()

    trainer = _create_trainer(precision=32, remove_checkpoint=False) # If remove_checkpoint is True, it works fine

    # Train the model ⚡
    trainer.fit(model, train, val)
    trainer.test(test_dataloaders=test)

def test_fp16():
    model = BoringModel()
    trainer16 = _create_trainer(precision=16)
    trainer16.fit(model, train, val)

test_normal()
test_another()
test_fp16()
```

See the comment in `test_another` to toggle the bug.
Also, if you run any function on its own it will finish fine.

### To Reproduce

See above

### Expected behavior

Either run or fail with error.

### Environment

**Note**: `Bugs with code` are solved faster ! `Colab Notebook` should be made `public` !

* `IDE`: None, terminal, python from conda.

* `Colab Notebook`: N/A

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
# For security purposes, please check the contents of collect_env_details.py before running it.
python collect_env_details.py
```

 - PyTorch Version (e.g., 1.0): 1.8.1+cu102
 - OS (e.g., Linux): Linux	
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.10
 - CUDA/cuDNN version: Not sure, I don't think I installed it, `nvidia-smi` says `11.2`
 - GPU models and configuration: 2 * 2080ti
 - Any other relevant information:

### Additional context

I found this during writing tests with `pytest`, but managed to reproduce without.

P.S. In `Trainer` doc-string it says that if file at `resume_from_checkpoint` doesn't exist, it will start from scratch, but in reality it throws an error. Need to correct doc-string or code.

P.P.S. Slack link in colab notebook also doesn't work.

**Comment by tchaton** [comment]
Hey @Rizhiy,

You shouldn't be running several DDP into the same scripts. They will create subprocesses and it will hang on a barrier somewhere causing 100 % GPU usage and no progress.

Would you trying with ddp_spawn, this shouldn't be a problem.

Best,
T.C

**Comment by Rizhiy** [comment]
Hi, this is primarily a problem in tests and changing to `ddp_spawn` just for tests is not ideal.

As you can see in the script, one trainer completely finishes before next one is started, so barrier should not be a problem. I think `Trainer` should kill all of its subprocesses on destruction.

**Comment by Rizhiy** [comment]
Also is it not possible to set up different trainers to communicate on different ports, so they don't clash?

**Comment by angadkalra** [comment]
This just happened to me too, I trained a model for 100 epochs, wanted to continue for another 100 so passed in the .ckpt path to Trainer resume_from_checkpoint arg and it kept freezing at the Trainer(...) call. I had to restart my VM to make it work.

**Comment by Rizhiy** [comment]
> Hey @Rizhiy,
> 
> You shouldn't be running several DDP into the same scripts. They will create subprocesses and it will hang on a barrier somewhere causing 100 % GPU usage and no progress.
> 
> Would you trying with ddp_spawn, this shouldn't be a problem.
> 
> Best,
> T.C
>  

This problem only happens when checkpoint is loaded, if you run the script without resuming from checkpoint it finishes successfully.

**Comment by Rizhiy** [comment]
Just tested and the problem happens with `dp` and `ddp_spawn` as well.

**Comment by Rizhiy** [comment]
Just checked, this doesn't happen on GPU, so must be some kind of GPU deadlock

**Comment by Rizhiy** [comment]
Also, doesn't happen with 1 GPU

**Comment by Rizhiy** [comment]
The freeze seems to happen on https://github.com/PyTorchLightning/pytorch-lightning/blob/04dcb1786d0ea41dfdb1e73493b214169e365c6c/pytorch_lightning/core/lightning.py#L1350

**Comment by Rizhiy** [comment]
If I comment out the following lines or set both variables to 0, the freeze doesn't happen:
https://github.com/PyTorchLightning/pytorch-https://github.com/PyTorchLightning/pytorch-lightning/blob/04dcb1786d0ea41dfdb1e73493b214169e365c6c/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L153-L154

**Comment by Rizhiy** [comment]
If I comment out only https://github.com/PyTorchLightning/pytorch-lightning/blob/04dcb1786d0ea41dfdb1e73493b214169e365c6c/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L154, the freeze still happens, but I also get an error:
```bash
Traceback (most recent call last):
  File "/home/rizhiy/projects/ntf/test_freeze.py", line 180, in <module>
    test_another()
  File "/home/rizhiy/projects/ntf/test_freeze.py", line 169, in test_another
    trainer.test(test_dataloaders=test)
  File "/home/rizhiy/projects/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 583, in test
    self.tested_ckpt_path = self.__load_ckpt_weights(ckpt_path)
  File "/home/rizhiy/projects/pytorch-lightning/pytorch_lightning/trainer/trainer.py", line 1167, in __load_ckpt_weights
    self.training_type_plugin.restore_model_state_from_ckpt_path(
  File "/home/rizhiy/projects/pytorch-lightning/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 231, in restore_model_state_from_ckpt_path
    ckpt = pl_load(ckpt_path, map_location=map_location)
  File "/home/rizhiy/projects/pytorch-lightning/pytorch_lightning/utilities/cloud_io.py", line 32, in load
    with fs.open(path_or_url, "rb") as f:
  File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/fsspec/spec.py", line 942, in open
    f = self._open(
  File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/fsspec/implementations/local.py", line 120, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/fsspec/implementations/local.py", line 202, in __init__
    self._open()
  File "/home/rizhiy/miniconda3/envs/ntf/lib/python3.8/site-packages/fsspec/implementations/local.py", line 207, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/55767507-345c-48be-ad91-2334f435cb89/lightning_logs/version_1/checkpoints/step=00029.ckpt'
```
Perhaps there is some kind of race condition happening?

**Comment by Rizhiy** [comment]
In my own code the freeze also happens on test, but commenting out the lines doesn't help.

**Comment by Rizhiy** [comment]
So it appears, that file exists when one process reaches it, but is missing when the other reaches the same line. Does `ModelCheckpoint` delete checkpoint files on destruction?

**Comment by Rizhiy** [comment]
> @tchaton Just tested and the problem happens with `dp` and `ddp_spawn` as well.

This turns out to be false, there is a bug in `pl.Trainer` (#7744), which caused my experiments to always use `ddp`.

`ddp_spawn` works fine, although a lot slower. Can't test `dp` because there is another bug somewhere in PL which causes `gather` to fail.

**Comment by Rizhiy** [comment]
Ok, I think I found the problem. I got a similar problem where checkpoint was not loading with `ddp_spawn` and I got an error from https://github.com/PyTorchLightning/pytorch-lightning/blob/ec4f8856afda7f988f0012b86b60ac634815b4f3/pytorch_lightning/trainer/connectors/checkpoint_connector.py#L75, which said that checkpoint didn't exist when it clearly does.
I'm not sure what `fsspec` is, but there is clearly a bug there and you should probably not be using it.

Replacing that check with `if not Path(checkpoint_path).exists()` solves the problem.

The path is: `/tmp/pytest-of-rizhiy/pytest-33/checkpoint_runner_output0/lightning_logs/version_0/checkpoints/last.ckpt`

**Comment by tchaton** [comment]
Dear @Rizhiy,

Thanks for looking deeper into it.
I will investigate tomorrow :)

Best,
T.C

**Comment by awaelchli** [comment]
The reason for the freeze here is that you are generating a checkpointing folder path with a call to `uuid()` and this is not deterministic, so each process will independently generate such a folder. When configuring the Trainer, you have

```python
resume_from_checkpoint=last_checkpoint_path if last_checkpoint_path.exists() else None,
```
where on one rank the folder exists and on the other it doesn't (it is different and we never saved anything there). The code path diverges on the ranks and we get a hang.

Instead of

```python
ckpt_dir = Path("/tmp") / str(uuid())
```

You can do

```python
from pytorch_lightning import seed_everything
from uuid import UUID
import random

seed_everything(123)
_uuid = UUID(int=random.getrandbits(128))

ckpt_dir = Path("/tmp") / str(_uuid)
```

I verified with your code sample.

**Comment by Rizhiy** [comment]
@awaelchli Hi, I'm not sure how to make it deterministic since this problem occurs inside pytest which generates a unique directory for each test.

**Comment by awaelchli** [comment]
Yes, we can't expect pytest to work with "ddp". When you specify accelerator="ddp" we expect that the user runs the code as a script, so that Lightning can call the script several times under the hood. 

You can use ddp_spawn alternatively, which should be ok for your use case. 

In our test suite here in Lightning, we call pytest in a special way. See https://github.com/PyTorchLightning/pytorch-lightning/blob/master/tests/special_tests.sh

**Comment by Kin-Zhang** [comment]
The problem still in lightning==2.0.1, with ddp to restore Trainer ckp

**Comment by R-N** [comment]
Still here on 2.1.2

**Comment by R-N** [comment]
I can't use ddp_spawn because I'm using Kaggle. Meanwhile dp seems to have been removed.
