### ISSUE TITLE
Training stuck at the begining

### ISSUE THREAD

**Issue by MendelXu** [PyTorchLightning/pytorch-lightning#8394]
### Discussed in https://github.com/PyTorchLightning/pytorch-lightning/discussions/8321

<div type='discussions-op-text'>

<sup>Originally posted by **MendelXu** July  7, 2021</sup>
When I use 2 GPUs, My training process is stuck at the beginning of the first epoch and even I am not able to kill it with ctrl+c. However, if I change it to 1 gpu or 4 gpu, it works fine. As there is no error information, how can I debug it and find the problem?</div>
After debugging line by line, I find that it will hang on at here https://github.com/PyTorchLightning/pytorch-lightning/blob/c5a120ed9d094ae152cc19902c4c4e969ca45a44/pytorch_lightning/plugins/training_type/ddp.py#L356
However, if I remove the callback, it works well. The callback is https://github.com/PyTorchLightning/pytorch-lightning/blob/c5a120ed9d094ae152cc19902c4c4e969ca45a44/pytorch_lightning/utilities/cli.py#L147

**Comment by tchaton** [comment]
Hey @MendelXu,

Would it be possible for you to share the code of the callback ?

It usually hangs when processes accross ranks diverged.

Best,
T.C

**Comment by awaelchli** [comment]
Was it solved by this PR?
https://github.com/PyTorchLightning/pytorch-lightning/pull/8017
I think this is not yet in any bugfix release. You could try to see if you issue is fixed with the master branch :)
