### ISSUE TITLE
Multi-node training freezes during ddp initialization

### ISSUE THREAD

**Issue by catalys1** [PyTorchLightning/pytorch-lightning#8707]
## 🐛 Bug

I'm trying to do multi-node training using SLURM. The job starts up, but it freezes during `ddp` setup. I'm trying to use 2 nodes with 4 GPUs each. It seems like it is able to get 4 GPUs initialized, and then hangs waiting for the rest. Here's the output I get:
```
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/8
initializing ddp: GLOBAL_RANK: 2, MEMBER: 3/8
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
initializing ddp: GLOBAL_RANK: 3, MEMBER: 4/8
```
And this is the output of `squeue`
```
JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
42859712       m9g      job.sh   catalys1  R         0:25   2 m9g-1-[3-4]
```
### To Reproduce

Here's a minimal test case. I'm only able to test this on the university system.

Training code.
```python
import logging
import os
import torch
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
import torchvision.transforms as transforms

import pytorch_lightning as ptl

def get_logger(name=__name__, level=logging.INFO):
    """Initializes python logger."""

    logger = logging.getLogger(name)
    logger.setLevel(level)

    # this ensures all logging levels get marked with the rank zero decorator
    # otherwise logs would get multiplied for each GPU process in multi-GPU setup
    for level in ("debug", "info", "warning", "error", "exception", "fatal", "critical"):
        setattr(logger, level, ptl.utilities.rank_zero_only(getattr(logger, level)))

    return logger


log = get_logger(__name__)

class CoolModel(ptl.LightningModule):

    def __init__(self):
        super(CoolModel, self).__init__()
        # not the best model...
        self.l1 = torch.nn.Linear(28 * 28, 10)

    def forward(self, x):
        return torch.relu(self.l1(x.view(x.size(0), -1)))

    def my_loss(self, y_hat, y):
        return F.cross_entropy(y_hat, y)

    def training_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        return {'loss': self.my_loss(y_hat, y)}

    def validation_step(self, batch, batch_nb):
        x, y = batch
        y_hat = self.forward(x)
        return {'val_loss': self.my_loss(y_hat, y)}

    def validation_end(self, outputs):
        avg_loss = torch.stack([x['val_loss'] for x in outputs]).mean()
        return {'avg_val_loss': avg_loss}

    def configure_optimizers(self):
        return [torch.optim.Adam(self.parameters(), lr=0.02)]

    def train_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)

    def val_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)

    def test_dataloader(self):
        return DataLoader(MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor()), batch_size=32)


from pytorch_lightning import Trainer
from test_tube import Experiment

model = CoolModel()

# train on cpu using only 10% of the data and limit to 1 epoch (for demo purposes)
trainer = Trainer(max_epochs=1, gpus=[0,1,2,3], num_nodes=2, accelerator='ddp')

trainer.fit(model)
```
And here's my SLURM job file.
```bash
#!/bin/bash

#SBATCH --time=00:10:00   # walltime
#SBATCH --ntasks-per-node=12   # number of processor cores (i.e. tasks)
#SBATCH --gpus=8
#SBATCH --mem-per-cpu=1536M   # memory per CPU core
#SBATCH --nodes=2
#SBATCH -C pascal
#SBATCH --qos=test

# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load python/3.8
module load cuda/10.1

source ~/venv/bin/activate

cd ~/test/

python test.py

```

### Expected behavior

Able to train successfully on multiple nodes

### Environment

PyTorch Lightning Version: `1.4.0`
PyTorch Version: `1.9.0`
Python Version: `3.8`
OS: `RedHat Linux`
CUDA Version: `10.1`
GPU models: `4xP100 per node`
Installed PyTorch via pip

**Comment by awaelchli** [comment]
Hi, these settings don't look right to me. 

Let's say you want exactly this, 4 gpus per node and 2 nodes totalling 8 gpus:
`trainer = Trainer(max_epochs=1, gpus=[0,1,2,3], num_nodes=2, accelerator='ddp')
`
that makes 4 tasks per node so in the slurm batch script it should be:

`#SBATCH --ntasks-per-node=4 
`
right?

**Comment by catalys1** [comment]
Hmm, you could be right. I'm new to SLURM, so I'm not sure. My understanding was that the `ntasks-per-node` was supposed to specifiy the number of CPU cores that I needed, but I could be wrong there. I'll try messing around with it and see what I can figure out.

**Comment by awaelchli** [comment]
To my knowledge it has nothing to do with CPUs. [Here](https://slurm.schedmd.com/sbatch.html) you can find the exact description of these arguments. Let me know how it goes.

**Comment by catalys1** [comment]
Ok, I tried changing the SBATCH commands to this:
```
#!/bin/bash

#SBATCH --time=00:010:00   # walltime
#SBATCH --ntasks-per-node=4 # number of processor cores (i.e. tasks)
#SBATCH --cpus-per-task=4
#SBATCH --gpus=8
#SBATCH --mem-per-cpu=1536M   # memory per CPU core
#SBATCH --nodes=2
#SBATCH -C pascal
#SBATCH --qos=test


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load python/3.8
module load cuda/10.1

source ~/venv/bin/activate

cd ~/test/

python test.py
```
The output is slightly different, but it still freezes:
```
Multi-processing is handled by Slurm.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/8
```

**Comment by nicolas-dufour** [comment]
Hey i had the same problem and i solved it by adding srun at the end before the python run.py. Apparently, there is no problem when you don't have the num_nodes args without the srun but it fails when you add it (For me it also failed when i specified num_nodes=1)

**Comment by catalys1** [comment]
@nicolas-dufour that solved it, thanks! Here's what I ended up using:
```bash
#!/bin/bash

#SBATCH --time=00:010:00   # walltime
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4 # number of processor cores (i.e. tasks)
#SBATCH --gpus=8
#SBATCH --mem=0   # memory per CPU core
#SBATCH -C pascal
#SBATCH --exclusive


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module load python/3.8
module load cuda/10.1

source ~/venv/bin/activate

cd ~/test/

srun python test.py
```

**Comment by jonathanking** [comment]
I've run into this issue on a SLURM cluster today, and all combinations of the suggested solutions have not allowed me to use multi-node, multi-gpu training. My project, unfortunately, is using pytorch-lightning 1.5, and I wonder if the problem lies therein.

**Comment by ramithuh** [comment]
A similar situation occurred to me (I read through  #8707, #19817, #10098, #4612 #6206, with no luck), even after making sure the following two points, my process was still stuck at the output shown at the very end [1]: 
1.  `--ntasks-per-node` = `Trainer.devices` , `--nodes= num_nodes`
2. make sure to do `srun python`

**However**, after discussions with perplexity, **It appears that NCCL was trying to communicate over an incorrect interface**. Therefore, suggested me to run `ip -o -4 addr show up | cut -d' ' -f2,7` to see which interfaces are present on the GPU nodes. The problem was that the cluster nodes had multiple network interfaces available, including virtual ones for container networking (`flannel.1`, `cni0`) in addition to the main physical one (`enp94s0f0`).

**So I had to explicitly specify the correct one as the following in the job script:**
- **`export NCCL_SOCKET_IFNAME=enp94s0f0`**

---- 

Finally my working bash script looked like this 

```
#!/bin/bash
#SBATCH --nodes=3
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4 # should match trainer.devices

#SBATCH --nodelist=gpu[01-04]
#SBATCH --cpus-per-task=4
#SBATCH --time=04:30:00
#SBATCH --mem=32G
#SBATCH --job-name=test

source ~/.bashrc
mamba activate test_env

# FIX : Force NCCL to use the correct physical network interface
export NCCL_SOCKET_IFNAME=enp94s0f0

srun python -u train.py \
     training.num_nodes=${SLURM_NNODES} \
     training.devices=${SLURM_NTASKS_PER_NODE} \
     training.epochs=50
```

For anyone facing similar issues, I'd suggest running `export NCCL_DEBUG=INFO` so that you can see what goes wrong.. 

----

<details>

<summary>[1] previous bash job output (stuck):</summary>

```
[rank: 11] Seed set to 42
[rank: 10] Seed set to 42
[rank: 8] Seed set to 42
[rank: 1] Seed set to 42
[rank: 2] Seed set to 42
[rank: 0] Seed set to 42
[rank: 4] Seed set to 42
[rank: 6] Seed set to 42
[rank: 7] Seed set to 42
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
Initializing distributed: GLOBAL_RANK: 8, MEMBER: 9/12
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
`Trainer(val_check_interval=1.0)` was configured so validation will run at the end of the training epoch..
Model: test_model, Parameters: 10,697,856
Initializing distributed: GLOBAL_RANK: 10, MEMBER: 11/12
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
Initializing distributed: GLOBAL_RANK: 4, MEMBER: 5/12
wandb: Currently logged in as: ruh_cmu (ruh_cmu-carnegie-mellon-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
Initializing distributed: GLOBAL_RANK: 11, MEMBER: 12/12
Initializing distributed: GLOBAL_RANK: 6, MEMBER: 7/12
Initializing distributed: GLOBAL_RANK: 7, MEMBER: 8/12
Initializing distributed: GLOBAL_RANK: 2, MEMBER: 3/12
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/12
wandb: Tracking run with wandb version 0.20.1
wandb: Run data is saved locally in ./wandb/
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ddp
wandb: ⭐️ View project at https://wandb.ai/<redacted>
wandb: 🚀 View run at https://wandb.ai/<redacted>/runs/
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/12
[rank: 9] Seed set to 42
[rank: 3] Seed set to 42
Model: test_model, Parameters: 10,697,856
Model: test_model, Parameters: 10,697,856
Initializing distributed: GLOBAL_RANK: 9, MEMBER: 10/12
Initializing distributed: GLOBAL_RANK: 3, MEMBER: 4/12
[rank: 5] Seed set to 42
Model: test_model, Parameters: 10,697,856
Initializing distributed: GLOBAL_RANK: 5, MEMBER: 6/12
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 12 processes
----------------------------------------------------------------------------------------------------
```

Job script 

```
#!/bin/bash
#SBATCH --nodes=3
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4 # should match trainer.devices

#SBATCH --nodelist=gpu[01-04]
#SBATCH --cpus-per-task=4
#SBATCH --time=04:30:00
#SBATCH --mem=32G
#SBATCH --job-name=test

source ~/.bashrc
mamba activate env_name

srun python -u train.py \
     training.num_nodes=${SLURM_NNODES} \
     training.devices=${SLURM_NTASKS_PER_NODE} \
     training.epochs=50
```

</details>

>
