### ISSUE TITLE
`RuntimeError: CUDA error: out of memory` on model instantiation when running on computing cluster

### ISSUE THREAD

**Issue by import-antigravity** [PyTorchLightning/pytorch-lightning#9262]
## 🐛 Bug
When running the provided script I get the following error:

```
(ganresearch) [@classt05 test]$ python oom_test.py
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
.../lib/python3.8/site-packages/pytorch_lightning/trainer/configuration_validator.py:99: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f"you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop")
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "oom_test.py", line 82, in <module>
    test_x(tmpdir)
  File "oom_test.py", line 78, in test_x
    trainer.fit(model=model, datamodule=dm)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File ".../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _call_setup_hook
    self.accelerator.barrier("pre_setup")
  File ".../lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 381, in barrier
    self.training_type_plugin.barrier(name=name)
  File ".../lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 350, in barrier
    torch.distributed.barrier(device_ids=self.determine_ddp_device_ids())
  File ".../lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2524, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: CUDA error: out of memory
```

### To Reproduce

I believe this is only an HPC problem, as running the code on a colab notebook does not cause the error. Here is the script:
```python
import pytorch_lightning as pl
from pytorch_lightning import LightningDataModule
from torch.nn import functional as F
from torchvision import transforms
from torchvision.datasets import MNIST

tmpdir = '../../data'


def mnist(root: str, normalize: bool = False):
    tlist = [transforms.ToTensor()]

    if normalize:
        tlist.append(transforms.Normalize((0.5,), (0.5,)))

    transform = transforms.Compose(tlist)

    trainset = MNIST(root=root, train=True, download=True, transform=transform)
    testset = MNIST(root=root, train=False, download=True, transform=transform)
    return trainset, testset


def mnist_datamodule(data_path: str, batch_size: int, num_workers: int):
    train, val = mnist(data_path, normalize=True)
    return LightningDataModule.from_datasets(train, val, None, batch_size=batch_size, num_workers=num_workers)


import torch
from pytorch_lightning import LightningModule


class BoringModel(LightningModule):

    def __init__(self):
        super().__init__()
        self.fc1 = torch.nn.Linear(28 * 28, 32)
        self.fc2 = torch.nn.Linear(32, 10)

    def forward(self, x):
        x = torch.flatten(x, 1)
        x = F.sigmoid(self.fc1(x))
        x = F.softmax(self.fc2(x))
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = F.cross_entropy(y_hat, y)
        return loss

    def training_step_end(self, training_step_outputs):
        return training_step_outputs

    def training_epoch_end(self, outputs) -> None:
        torch.stack([x["loss"] for x in outputs]).mean()

    def configure_optimizers(self):
        optimizer = torch.optim.SGD(self.parameters(), lr=0.01)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def test_x(tmpdir):
    # init model
    model = BoringModel()

    # Initialize a trainer
    trainer = pl.Trainer(
        max_epochs=1,
        progress_bar_refresh_rate=20,
        gpus=2,
        accelerator='ddp'
    )

    dm = mnist_datamodule(tmpdir, 16, 1)

    # Train the model ⚡
    trainer.fit(model=model, datamodule=dm)


if __name__ == '__main__':
    test_x(tmpdir)
```

### Expected behavior

Clearly the model is very small and should not lead to an OOM. I'm getting similar errors outside of training contexts using a PTL model and calling `.cuda()`.

### Environment

```
* CUDA:
	- GPU:
		- GeForce RTX 2080 Ti
		- GeForce RTX 2080 Ti
	- available:         True
	- version:           10.2
* Packages:
	- numpy:             1.21.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.9.0
	- pytorch-lightning: 1.4.1
	- tqdm:              4.62.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.8.0
	- version:           #1 SMP Tue Feb 18 16:39:12 EST 2020
```

**Comment by tchaton** [comment]
Hey @import-antigravity,

I confirm it works fine for me. You might want to sync with your cluster management team and investigate with them.

```py
(.venv) thomas@hyperplane1:~/pytorch-lightning$ python test.py 
GPU available: True, used: True
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
IPU available: False, using: 0 IPUs
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/MNIST/raw/train-images-idx3-ubyte.gz
9913344it [00:00, 36966131.28it/s]                                                                                                                                              
Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to data/MNIST/raw/train-labels-idx1-ubyte.gz
29696it [00:00, 54248280.31it/s]                                                                                                                                                
Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to data/MNIST/raw/t10k-images-idx3-ubyte.gz
1649664it [00:00, 29075168.56it/s]                                                                                                                                              
Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw

Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to data/MNIST/raw/t10k-labels-idx1-ubyte.gz
5120it [00:00, 22676701.67it/s]                                                                                                                                                 
Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw

/home/thomas/pytorch-lightning/.venv/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
/home/thomas/pytorch-lightning/pytorch_lightning/trainer/configuration_validator.py:120: UserWarning: you passed in a val_dataloader but have no validation_step. Skipping val loop
  rank_zero_warn(f"you passed in a {loader_name} but have no {step_name}. Skipping {stage} loop")
/home/thomas/pytorch-lightning/pytorch_lightning/core/datamodule.py:212: LightningDeprecationWarning: DataModule property `has_prepared_data` was deprecated in v1.4 and will be removed in v1.6.
  rank_zero_deprecation(
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2
/home/thomas/pytorch-lightning/.venv/lib/python3.8/site-packages/torchvision/datasets/mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 2 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]

  | Name | Type   | Params
--------------------------------
0 | fc1  | Linear | 25.1 K
1 | fc2  | Linear | 330   
--------------------------------
25.4 K    Trainable params
0         Non-trainable params
25.4 K    Total params
0.102     Total estimated model params size (MB)

  | Name | Type   | Params
--------------------------------
0 | fc1  | Linear | 25.1 K
1 | fc2  | Linear | 330   
--------------------------------
25.4 K    Trainable params
0         Non-trainable params
25.4 K    Total params
0.102     Total estimated model params size (MB)
/home/thomas/pytorch-lightning/pytorch_lightning/core/hooks.py:694: LightningDeprecationWarning: Method `on_train_dataloader` in DataHooks is deprecated and will be removed in v1.7.0. Please use `train_dataloader()` directly.
  rank_zero_deprecation(
/home/thomas/pytorch-lightning/pytorch_lightning/trainer/data_loading.py:111: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 255 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                               | 0/1875 [00:00<00:00, 4382.76it/s]/home/thomas/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/nn/functional.py:1805: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
test.py:42: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.fc2(x))
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
/home/thomas/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/nn/functional.py:1805: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/thomas/pytorch-lightning/test.py:42: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.fc2(x))
[W reducer.cpp:1158] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
Epoch 0:  25%|██████████████████████████                                                                                | 460/1875 [00:08<00:27, 51.84it/s, loss=2.3, v_num=204]
```

**Comment by import-antigravity** [comment]
I've been running some tests and it's likely a problem with a specific compute node. I'll leave the issue open until I hear back but it's likely not PTL.

**Comment by import-antigravity** [comment]
It was a bad compute node! Sorry for the inconvenience! 😄

**Comment by import-antigravity** [comment]
It was a bad compute node! Sorry for the inconvenience! 😄
