### ISSUE TITLE
SWA callback triggers OOM on train end

### ISSUE THREAD

**Issue by talhaanwarch** [PyTorchLightning/pytorch-lightning#9441]
I am facing a problem that my system give cuda error in last epoch.
I have tried different system like ubunto or window, but error is there. I tried downgrading version, but error is not resolved fully.
Pytorch Lightning version: 1.4.5
torch version : 1.7.1
 OS: windows10 and ubunto 20

The more details are available in following link, as i am not getting any update in discussion section, and my work is completely stopped because of this error, so i decided to open an issue. 
https://github.com/PyTorchLightning/pytorch-lightning/discussions/9048#discussioncomment-1289908

**Comment by carmocca** [comment]
This could be caused by anything. I suggest you try removing code until the problem stops appearing to try and narrow the set of possibilities.

You can also try and collect the existing objects in CUDA memory to see if you get any hints:

```python
def recursively_traverse_for_dtype(obj, func, dtype):

    """
    This function is used to introspect an object attributes recursively looking a specific dtype.
    For each instance found, a function would be applied and the result will be stored
    in the attribute path to find back this object.
    """

    if isinstance(obj, dtype):
        return func(obj)
    if isinstance(obj, Collection) and not isinstance(obj, str):
        updated = apply_to_collection(
            obj,
            object,
            partial(recursively_traverse_for_dtype, func=func, dtype=dtype),
            wrong_dtype=Collection,
            include_none=False,
        )
    else:
        updated = {}
        try:
            for k, v in obj.__dict__.items():
                if isinstance(v, dtype):
                    updated[k] = func(v)
                else:
                    try:
                        updated[k] = recursively_traverse_for_dtype(v, func, dtype)

                    except AttributeError:
                        pass
        except AttributeError:
            pass
    return updated

def find_memory_leak():
    import gc
    for obj in gc.get_objects():
        try:
            def find_tensors(obj):
                if obj.device.type == "cuda":
                    print(obj)
                
            recursively_traverse_for_dtype(obj, find_tensors, torch.Tensor)
        except:
            pass
```

Without a way to reproduce it, there's not much we can do to help.

**Comment by talhaanwarch** [comment]
I tried this, and i think setting stochastic_weights_avg to False, resolve this issue. but i am not sure, its the permanent solution or not. But this is not so simple as stated that setting patience in EarlyStopping as 1 resolved the issue [here](https://github.com/PyTorchLightning/pytorch-lightning/discussions/9048#discussioncomment-1289908), but that was temporary

**Comment by carmocca** [comment]
So to recap, you see a large memory increase just before training ends when SWA is enabled, correct?

If that is the case, it would likely be happening here:

https://github.com/PyTorchLightning/pytorch-lightning/blob/b294c5760eee30a995fcd400127be209b12c4d7c/pytorch_lightning/callbacks/stochastic_weight_avg.py#L227-L236

Can you try printing the memory after each line to try and pinpoint which one causes it? That is if my hypothesis is correct.

**Comment by talhaanwarch** [comment]
yes, i again test it with a different data and SWA is causing the error.

**Comment by carmocca** [comment]
@cwerner We need a reproducible example to see what's the problem, if you can write it, we would appreciate it 👍

**Comment by cwerner** [comment]
Hi @carmocca 

Seems that the issue went away after updating to the most recent release. I was still on < 1.4 before. Issue can be closed.

Cheers

**Comment by austinmw** [comment]
@carmocca Hi, I'm also getting `CUDA out of memory.` error on the last epoch when using StochasticWeightAveraging callback.

**Comment by patrickFuerst** [comment]
@carmocca, Just mentioning that I still have the same issue with version `1.7.0`. OOM only happens when using `StochasticWeightAveragingConfig`. While training, I roughly use 2 GB of memory and in the last epoch it tries to allocate more than 11 GB.

**Comment by patrickFuerst** [comment]
For people maybe having the same issue. I was able to resolve it. 
The issue for me was using a `torchmetrics.MetricCollection` for my training metrics and calling `update(preds,y)`. 
After I changed it to  `update(preds.detach(),y)`, there was now OOM error anymore.

**Comment by gyu-eun-lee** [comment]
[swa_example.zip](https://github.com/Lightning-AI/lightning/files/10695613/swa_example.zip)

I have run into this issue on version `1.9.0`. I've uploaded an example to reproduce. It's hardly minimal, but I think I've isolated a possible cause. I find it very unintuitive, but as far as I can tell the SWA callback behaves strangely when training a convolutional NN but is fine with a fully connected NN.

Example description:
* The subdirectory `data` contains datasets used in the example notebooks.
* `convolutional.ipynb` and `fully_connected.ipynb` are two notebooks each implementing the same multilabel text classification task. The input cells are exactly identical except for the cell containing the model definition (`class EmbeddingClassifier(nn.Module): ...`).
* `convolutional.ipynb` contains an embedding layer (`torch.nn.Embedding`), two convolutional layers, and a linear layer for output.
* `fully_connected.ipynb` contains an embedding layer bag layer (`torch.nn.EmbeddingBag`), a number of linear layers, and a final linear layer for output.
* Both networks also contain batch normalization, activation, and dropout layers in comparable locations. They have comparable sizes.
* A conda env configuration is included.

Behavior:

* With the SWA callback, the convolutional NN gives an OOM error shortly into the last training epoch. During earlier epochs it is well under half of my GPU's memory capacity, for as many epochs as desired.
* The fully connected NN has no memory issues, and can be scaled up to GPU memory capacity.
* Neither notebook runs into an OOM if the SWA callback is commented out in the trainer.
* The difference in the embedding layers is not the issue. I tested this by testing a fully connected network with the same embedding layer as the convolutional NN, and it had no errors.
* If I tune the convolutional layer sizes to make the model extremely small (under 700k learnable params), the OOM does not occur.

OS is Ubuntu 22.04 LTS. GPU is GeForce GTX 1650 with 4GB RAM. If your GPU has more memory, I expect you may need to increase the size of the model to reproduce. The model is configured in the cell `config = ModelDataConfig(...`. The model size parameters are `vocab_length`, `max_length`, `embedding_dim` for the CNN, and also `hidden_dim` for the FCNN.
